apiVersion: v1
kind: Pod
metadata:
  name: better-http-server
  labels: {
    "app":"better-http-server"
  }
spec:
  containers:
    - name: better-http-server
      image: 769460962/myhttpserver:v4.3
      readinessProbe:
        httpGet:
          ### this probe will fail with 404 error code
          ### only httpcode between 200-400 is retreated as success
          path: /healthz
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 5
        successThreshold: 2
      livenessProbe:
        httpGet:
          path: /livez
          port: 80
        failureThreshold: 1
        periodSeconds: 10
      resources:
        requests:
          cpu: "200m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "200Mi"
      ports:
        - containerPort: 80    
